# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analitica_pb2 as analitica__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analitica_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnaliticaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDistribucionPorProvincia = channel.unary_unary(
                '/analitica.AnaliticaService/GetDistribucionPorProvincia',
                request_serializer=analitica__pb2.FiltroRequest.SerializeToString,
                response_deserializer=analitica__pb2.DistribucionResponse.FromString,
                _registered_method=True)
        self.GetFrecuenciaPorArma = channel.unary_unary(
                '/analitica.AnaliticaService/GetFrecuenciaPorArma',
                request_serializer=analitica__pb2.FiltroRequest.SerializeToString,
                response_deserializer=analitica__pb2.DistribucionResponse.FromString,
                _registered_method=True)
        self.GetAniosDisponibles = channel.unary_unary(
                '/analitica.AnaliticaService/GetAniosDisponibles',
                request_serializer=analitica__pb2.FiltroRequest.SerializeToString,
                response_deserializer=analitica__pb2.AniosResponse.FromString,
                _registered_method=True)
        self.GetConteoPorCategoria = channel.unary_unary(
                '/analitica.AnaliticaService/GetConteoPorCategoria',
                request_serializer=analitica__pb2.FiltroRequest.SerializeToString,
                response_deserializer=analitica__pb2.ConteoCategoriasResponse.FromString,
                _registered_method=True)


class AnaliticaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDistribucionPorProvincia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFrecuenciaPorArma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAniosDisponibles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConteoPorCategoria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnaliticaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDistribucionPorProvincia': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistribucionPorProvincia,
                    request_deserializer=analitica__pb2.FiltroRequest.FromString,
                    response_serializer=analitica__pb2.DistribucionResponse.SerializeToString,
            ),
            'GetFrecuenciaPorArma': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFrecuenciaPorArma,
                    request_deserializer=analitica__pb2.FiltroRequest.FromString,
                    response_serializer=analitica__pb2.DistribucionResponse.SerializeToString,
            ),
            'GetAniosDisponibles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAniosDisponibles,
                    request_deserializer=analitica__pb2.FiltroRequest.FromString,
                    response_serializer=analitica__pb2.AniosResponse.SerializeToString,
            ),
            'GetConteoPorCategoria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConteoPorCategoria,
                    request_deserializer=analitica__pb2.FiltroRequest.FromString,
                    response_serializer=analitica__pb2.ConteoCategoriasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analitica.AnaliticaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analitica.AnaliticaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnaliticaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDistribucionPorProvincia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica.AnaliticaService/GetDistribucionPorProvincia',
            analitica__pb2.FiltroRequest.SerializeToString,
            analitica__pb2.DistribucionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFrecuenciaPorArma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica.AnaliticaService/GetFrecuenciaPorArma',
            analitica__pb2.FiltroRequest.SerializeToString,
            analitica__pb2.DistribucionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAniosDisponibles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica.AnaliticaService/GetAniosDisponibles',
            analitica__pb2.FiltroRequest.SerializeToString,
            analitica__pb2.AniosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConteoPorCategoria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica.AnaliticaService/GetConteoPorCategoria',
            analitica__pb2.FiltroRequest.SerializeToString,
            analitica__pb2.ConteoCategoriasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
